### ISSUE TITLE
I wanted to ask which languages this tool supports? Can we use it for languages other than English?

### ISSUE THREAD

**Issue by Mehdi0xC** [baxtree/subaligner#46]
I wanted to ask which languages this tool supports? Can we use it for languages other than English?

**Comment by baxtree** [comment]
Hi, @Mehdi0xC, Thanks for your interest in subaligner. Yes and for that to work, try switching off the stretching on dual-stage alignment with the `-so` flag:
`$ subaligner_2pass -v video.mp4 -s subtitle.srt -so`
or
`$ subaligner -m dual -v video.mp4 -s subtitle.srt -so`
Single-stage alignment is language agnostic by default. More details on the usage can be found in [here](https://subaligner.readthedocs.io/en/latest/usage.html).

**Comment by baxtree** [comment]
Hi, @Mehdi0xC , now you can pass in the language code via `-sil` or `--stretch_in_language`, which is used for stretching by the dual-stage alignment. More details can be found by running `subaligner -h`.
