### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Shawn9347** [baxtree/subaligner#59]
Hello,

I installed subaligner with pip and with docker. Both aren't working. 

This is the error I get when using it with pip. Command: subaligner -m dual -v "/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better Call Saul/Season 2/Better Call Saul - 2x02 - Cobbler.mkv" -s "/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better Call Saul/Season 2/Better Call Saul - 2x02 - Cobbler.en.srt" -o "/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better Call Saul/Season 2/Better Call Saul - 2x02 - Cobbler.en.srt"

![image](https://user-images.githubusercontent.com/48714886/114858255-850b8e80-9de9-11eb-8ad9-a6c26afc3286.png)

This is the error I get with docker. Command: docker run -v `pwd`:`pwd` -w `pwd` -it baxtree/subaligner subaligner_2pass -v "/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better Call Saul/Season 2/Better Call Saul - 2x02 - Cobbler.mkv" -s "/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better Call Saul/Season 2/Better Call Saul - 2x02 - Cobbler.en.srt"

![image](https://user-images.githubusercontent.com/48714886/114858492-d025a180-9de9-11eb-9561-c8467cf3d125.png)

**Comment by baixiac** [comment]
Hi, @Rickexe , 
Seemingly you are missing bz2 headers after installing python. Now sure which distro you are running and assuming you are on Ubuntu, try to install the headers with `sudo apt-get install -y libbz2-dev`.

Subaligner cannot handle whitespace in the file path properly atm so removing/replacing them should make your command work. E.g., 
`/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better_Call_Saul/Season_2/Better_Call_Saul_-_2x02_-_Cobbler.mkv`
`/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better_Call_Saul/Season_2/Better_Call_Saul_-_2x02_-_Cobbler.en.srt`

**Comment by baxtree** [comment]
Hi, @Rickexe ,
Seemingly you are missing bz2 headers after installing python. Now sure which distro you are running and assuming you are on Ubuntu, try to install the headers with `sudo apt-get install -y libbz2-dev`.

Subaligner cannot handle whitespace in the file path properly atm so removing/replacing them should make your command work. E.g.,
`/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better_Call_Saul/Season_2/Better_Call_Saul_-_2x02_-_Cobbler.mkv`
`/srv/86328239-e681-4586-8c7b-bf01e82bce9e/TvShows/Better_Call_Saul/Season_2/Better_Call_Saul_-_2x02_-_Cobbler.en.srt`

**Comment by Shawn9347** [comment]
I already installed the "libbz2-dev" package but I still get the error.

**Comment by baxtree** [comment]
Could you provide the following information?
* Operating System
* Python Version

**Comment by Shawn9347** [comment]
I am using Openmediavault which is based on debian and my Python version is 2.7.16.

**Comment by Shawn9347** [comment]
![image](https://user-images.githubusercontent.com/48714886/114995801-7cc15b00-9e9e-11eb-95ee-e7214f7064eb.png)

**Comment by baixiac** [comment]
Subaligner only supports Python 3.6 onwards. Please upgrade your python and try again.

**Comment by baxtree** [comment]
Subaligner only supports Python 3.6 onwards but not 3.9 yet. Please upgrade your python and try again.

**Comment by Shawn9347** [comment]
I also have python 3.6 installed.

**Comment by Shawn9347** [comment]
But how do I run it with python 3.6?

**Comment by baxtree** [comment]
You can create a virtual environment using your python 3.6 before installation, as shown in the [README screencast:](https://github.com/baxtree/subaligner/blob/master/figures/screencast.gif).

**Comment by Shawn9347** [comment]
Ok I tried that. I get the same error.

![image](https://user-images.githubusercontent.com/48714886/114997798-85b32c00-9ea0-11eb-9a60-00dd87ff10ab.png)

**Comment by baxtree** [comment]
Did you rebuild your python after installing `libbz2-dev`? Apparently, your python 3.6 cannot find the bz2 header either. I would suggest reinstalling a fresh copy of python 3 and see how that goes.

**Comment by Shawn9347** [comment]
I'll try later. If I uninstall python now everything will break.

**Comment by baxtree** [comment]
Hi, @Rickexe , how is it going with your installation? BTW, the `development` branch should have understood the whitespace in the file path by now.

**Comment by Shawn9347** [comment]
Thank you for asking. I haven't done much tbh. My apt is broken on my server and I can't even access the omv admin panel. Only way to recover is reset probably but I'll probably get a new server soon so I don't want to reinstall everything right now. Maybe I'll try it tomorrow on Ubuntu in Windows 10.

**Comment by Shawn9347** [comment]
![image](https://user-images.githubusercontent.com/48714886/115518883-f5eaf480-a288-11eb-8c4a-109b8d5dd730.png)

It's working! I ran it on a subtitle and it does need some adjustments but it's a lot better than any of the other dozen sub sync project I have tried. Thank you

**Comment by baxtree** [comment]
Glad to know it is working for you and thanks for confirming it now can handle file paths containing whitespace.

**Comment by Shawn9347** [comment]
I have to say. It is working but the subs aren't aligned correctly. I am using the dual method. Sometimes it's too fast sometimes too slow. I really don't understand why subtitles from subscene, opensubtitles and pretty much every provider are off by so much. Some sentences are like 5 seconds too early. How?

**Comment by baxtree** [comment]
Does the speed vary on aligning different audio/video files or the same file across multiple runs? The majority of running time will be spent on extracting features from audiovisual content and if you have a long video with subtitles containing lots of gaps in between, it won't be very fast. Increasing the number of workers may expedite the process (prepending `MAX_WORKERS=X` to your subaligner command) but only if you have more cores on your machine.

For QC, if copyright and data protection policy allow, feel free to share your media files and I can have a look at the mis-aligning. I haven't checked the subtitle quality on subscene or opensubtitles so I cannot make any comments about your observation.

**Comment by Shawn9347** [comment]
No, what I mean is that the subs are out of sync. I ran your script on one of my srt files, that command I posted in this thread and it's working but the subs are still out ot sync.

**Comment by baxtree** [comment]
Hi, @Rickexe, Have you tried the dual mode with the `-so` or `--stretch_off` flag? It will switch off some experimental feature which may not be needed for your case. Please let me know if that helps and if not I need to investigate more into your media files before say anything sensical.

**Comment by Shawn9347** [comment]
Hi, I tried the dual mode with the flag. It's still way out of sync. Like 3 seconds or so. I uploaded the mkv and srt on google drive. Let me know if it works for you. 

srt:
[REDACTED]

mkv:
[REDACTED]

The first speech in the file is on 2:09.

**Comment by baxtree** [comment]
I think your case has made the tool reached its limit. With `--debug` on, the log shows the final log loss is greater than 0.82 which is too high and indicating the failure. A successful alignment should end up with a log loss between 0.3 and 0.5. You could pass in `--max_logloss 0.5` to make the command fail.

Looking closely at the subtitle segments ahead of the theme song kicking in, some of them last very long, e.g., the first one: `Subtitle chunk #0: start time: 00:02:06,520 ------> end time: 00:02:49,520`. The cue gaps inside that segment are around 300 ms so there are not big enough gaps for subligner to manoeuvre the shift. Nonetheless, the output to me is still better coz some cues did get aligned compared with the totally out-of-sync input. After the theme song finishes, the subtitle is aligned well but looks like the input subtitle have got that part roughly in sync already.

**Comment by baxtree** [comment]
Hi, @Rickexe . Looks like manually splitting the video and the subtitle into two parts and aligning them separately helped but the output is still not perfect. The non-speech content skewed part of the alignment but you can always [train your own subaligner ](https://subaligner.readthedocs.io/en/latest/advanced_usage.html) to detect more miscellaneous ambient sound. Given this issue is originally about installation, I am closing it for now. Feel free to open another issue if you have more findings.
