### ISSUE TITLE
[Suggestion] Is there a way to run in batch mode?

### ISSUE THREAD

**Issue by Ruke805** [baxtree/subaligner#62]
It would be nice if were possible to run in batch mode, like, sync all files in a folder and subfolders, for example for tv shows with seasons directories. I've searched in the documentation but found nothing about it and maybe would be a good feature.

**Comment by baxtree** [comment]
Hi, @theruleof4 , Thanks for the suggestion! The training is already looking at folders and porting that logic to the alignment should be quite straightforward. So let's keep this issue open and PRs are welcome.

**Comment by Ruke805** [comment]
It would be awesome indeed

**Comment by baxtree** [comment]
Hi, @theruleof4 , just let you know that batch alignment has been supported since `v0.1.16`.
`$ pip install -U subaligner`
`$ subaligner_batch -m single -vd videos/ -sd subtitles/ -od aligned_subtitles/`
`$ subaligner_batch -m dual -vd videos/ -sd subtitles/ -od aligned_subtitles/`

**Comment by baxtree** [comment]
Closing this issue as resolved by [v0.1.16](https://github.com/baxtree/subaligner/releases/tag/v0.1.16).
