### ISSUE TITLE
Update numpy to 1.22.0 in requirements.txt

### ISSUE THREAD

**Issue by Shidouuu** [baxtree/subaligner#70]
1.22.0 includes support for python 3.9-3.10

**Comment by baxtree** [comment]
The numpy range as been [widened](https://github.com/baxtree/subaligner/blob/e7eada5969bb84f170c1ba5b60df4fba1e2f2b1f/requirements.txt#L41). However, subaligner has yet to support python 3.10 due to pytorch's issue#66424.
