### ISSUE TITLE
[Suggestion] Use embeded subtitles for training model if present

### ISSUE THREAD

**Issue by arabcoders** [baxtree/subaligner#72]
Hello, I use your official docker container, and noticed that subaligner_train uses separate video and subtitles, right now i have to run separate script to extract the subtitles from video files rename them to be same as original video file, and then run the training model.

If it possible could you add support to use embedded subtitles?

Thank you.

**Comment by baxtree** [comment]
Thanks for trying out the trainer and that would be a nice feature to have on model training indeed. Currently the embedded subtitles are only supported during synchronisation, i.e., model prediction. Just out of my curiosity, which video format have you used for embedding subtitles?

**Comment by arabcoders** [comment]
@baxtree Thank you for your fast response. its mostly mp4/mkv files.

**Comment by baxtree** [comment]
Oh cool. I believe that the syncing has supported extraction of subtitles in both formats. It shall be quite straightforward to reuse that in preparing the training dataset.

**Comment by baxtree** [comment]
Hi, @ArabCoders, The support for training over subtitle-embedded video files has been merged into the master branch.  If you wanna try it, please install subaligner locally and run:

`$ subaligner_train -vd av_directory -ess embedded:stream_index=0,file_extension=srt -tod training_output_directory`

, where `embedded:stream_index=0,file_extension=srt` is the subtitle selector which specifies the embedded subtitle is located at stream 0 (the first subtitle track) and will be extracted as a SubRip file pre and post synchronisation.

**Comment by arabcoders** [comment]
@baxtree Thank you very much, is the docker container updated as well? i use it as base to to then include cuda for faster processing

**Comment by baxtree** [comment]
Yes @ArabCoders . Have got all docker images updated with this change.

**Comment by arabcoders** [comment]
> Yes @ArabCoders . Have got all docker images updated with this change.

Thank you.
