### ISSUE TITLE
Text to Audio alignment in different language

### ISSUE THREAD

**Issue by C00reNUT** [baxtree/subaligner#83]
Hello,

thank you for this nice tool!

I am trying to align matching text and audio files, both in the same language, which is not English. 

Is there a way so I could use this library to this alignment? Is there a way to change epeak language option from cli? 
And if so is that enough, or do I need to retrain the model?

Thank you!

**Comment by C00reNUT** [comment]
Seeing the cli options, is it enough to set -ml language code?

`subaligner -m script -v audio.mp3  -s text.txt -o subtitle_aligned.srt -ml ces`

Or do I need to specify some other options?

**Comment by C00reNUT** [comment]
Also when aligning big files cca 20hours of audio, the text doesn't align. I was hoping this library could cope with huge files, I have tried aeneas before, but it starts to fail at around 2 hour mark... 

```
1
00:00:00,000 --> 00:00:00,000
Na začátku je strach.

2
00:00:00,000 --> 00:00:00,000
Strach, že se utopím.

3
00:00:00,000 --> 00:00:00,000
Strach z ostatních – z těch, kteří mě nenávidí, a z těch, kteří chtějí mou kůži.

4
00:00:00,000 --> 00:00:00,000
A taky strach z pravdy.

5
00:00:00,000 --> 00:00:00,000
Na začátku je strach

6
00:00:00,000 --> 00:00:00,000
Na ostrov se nikdy nevrátím, i kdyby přišla k mým dveřím zazvonit Jennifer Lawrencová osobně a prosila mě, abych se tam vrátil, tak to nikdy neudělám.

7
00:00:00,000 --> 00:00:00,000
A ještě vám musím říct jedno: To, co vám budu vyprávět, vám bude připadat neuvěřitelné.

8
00:00:00,000 --> 00:00:00,000
Netvrdím, že to není banální příběh.

9
00:00:00,000 --> 00:00:00,000
To ne.

10
00:00:00,000 --> 00:00:00,000
Je to zkurvenej příběh.

11
00:00:00,000 --> 00:00:00,000
Jo, zkurvenej příběh…

```

**Comment by baxtree** [comment]
Hi, @C00reNUT, Thanks for your interest in Subaligner. Your command looks good to me. In the `script` mode where forced-alignment on texts and audio/video is applied, the language code is required and can be passed in via `-ml` or `-sil`.

The time-code problem is interesting... It's difficult if not impossible for me to investigate that without seeing the audio and script files. Nonetheless, does it sound more towards the dependency issue and if yes, could aeneas's github repo be the better place for reporting it?

**Comment by C00reNUT** [comment]
I was looking into this and if this library uses aeneas for force alignment, then it's definitely a dependency issue. 

Aeneas clearly doesn't handle files longer than 1-2 hours in length https://github.com/readbeyond/aeneas/issues/243 

I was hoping that this repo uses aeneas only as inspiration, thank you for your time!

**Comment by baxtree** [comment]
Yes, people have long waited for its next release but the dev is still dormant. Although it works for shorter audio, we will continue looking for other options. Subaligner's `dual` mode chops long audio into smaller chunks with the option of calling aeneas thereafter but only if there are long enough cue gaps.
