### ISSUE TITLE
Not able to install `subaligner[stretch]` on WSL Ubuntu 24.04

### ISSUE THREAD

**Issue by danbeibei** [baxtree/subaligner#90]
# Description
I'm not able to install `subaligner[stretch]` on WSL Ubuntu 24.04.
The installation process fails on the `aeneas` dependency.
I'm using pipx to install the package in a virtual environment.

# Reproduce
I use the following command: 
`$ pipx install --python python3.11 --fetch-missing-python 'subaligner[stretch]'`
I explicitly ask for Python 3.11 because the dependency `tornado` does not seem to support Python 3.12 (which is the default Python version for this OS). 

This command gives the following error when trying to install the dependency `aeneas`.
```
Collecting aeneas~=1.7.3.0 (from subaligner[stretch])
  Using cached aeneas-1.7.3.0.tar.gz (5.5 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      [ERRO] You must install numpy before installing aeneas
      [INFO] Try the following command:
      [INFO] $ sudo pip install numpy
      [end of output]
```

I figured I could install `subaligner` (without optional dependencies) first, and then add `subaligner[stretch]`. This way, `numpy` would already be installed when pip tries to install `aeneas`:
```
$ pipx install --python python3.11 --fetch-missing-python 'subaligner'
[...]
$ pipx inject --force subaligner 'subaligner[stretch]'
```

The first command run without error.
At the second command, I get the following error when pip gets to the point of installing `aeneas`:
```
File "/home/*****/.local/share/pipx/venvs/subaligner/lib/python3.11/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
```
Please tell me if more traceback is needed.
I'm not sure to understand why it is looking for the MSVC compiler as this runs in WSL.

- Can you help me understand what I'm doing wrong?
- How can I workaround those errors?

# Environment
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
```
```
$ uname -a
Linux ***** 4.4.0-19041-Microsoft #4355-Microsoft Thu Apr 12 17:37:00 PST 2024 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ pipx --version
1.6.0
```
```
$ python3 --version
Python 3.12.3
```
As stated above, I'm actually using python 3.11 for the virtual environment

The Windows host in case it is of any help:
`Windows 10 Professional 22H2, build 19045.4780`

**Comment by baxtree** [comment]
Thanks for reporting this. The error looks specific to the usage of WSL. Which version of `setuptools` have you installed? There seems to be a [workaround](https://github.com/numpy/numpy/issues/22135) through version pinning but hopefully a long-term solution exists.

**Comment by danbeibei** [comment]
Thank you for pointing that out. 
`setuptools` version `74.1.1` was installed by default. I forced `setuptools` version to `<65` and then ran into another problem: a missing library. That pointed to me failing to install the dependency mentioned in the README (espeak libespeak1 libespeak-dev espeak-data). With those dependencies actually installed, the `ModuleNotFoundError: No module named 'distutils.msvccompiler'` error doesn't even show up, and everything looks good. This was a mistake on my side. 
Thank you for your help.
