### ISSUE TITLE
Transcribed subtitles desync from audio

### ISSUE THREAD

**Issue by starptr** [baxtree/subaligner#91]
### Describe the bug
When using the transcriber, there seems to be a desync of the subtitles and the audio. Some of it might be from errors in the LLM,  but perhaps the audio extraction has a bug. I am suspecting this because [auto-subtitle](https://github.com/m1guelpf/auto-subtitle), a similar project to subaligner, has the same issue, and after [applying a fix in my own fork](https://github.com/starptr/auto-subtitle/blob/2e4989692d9abd207d01a5dd0819ccf67541b603/auto_subtitle/cli.py#L85), the majority of desync issues are fixed.

### To Reproduce
The command I'm running is:
```bash
subaligner -m transcribe -v video.mkv -ml deu -mr whisper -mf medium -o subtitles.srt
```
where `video.mkv` has an hevc video stream and an aac audio stream. (There are multiple audio streams, but subaligner seems to correctly select the desired audio stream for now. Does it know from the stream metadata which audio stream is correct based on the language?)

The audio stream is about 2 seconds shorter than the video stream, which is about the offset that the subtitles feel like they're desynced by.

### Expected behavior
The subtitles should be mostly in sync with the audio. Although the LLM transcription may contain minor timing errors, overall the subtitles should be mostly be in sync.

### Screenshots and logs
The CLI proceeds as expected.

### Media files
This is difficult, as I cannot share the specific video that I notice this issue on. Perhaps I will try to find a repro if necessary.

### Desktop (please complete the following information):
 - Operating System aarch64 MacOS 14.2.1
 - Python Version 3.9.6

### Additional context
My solution was to pass `-af aresample=async=1:min_hard_comp=0.100000:first_pts=0` to the ffmpeg CLI call when extracting the audio stream in a different project listed above. However, I am not sure if this is actually correct in the general case.

**Comment by baxtree** [comment]
Hi @starptr, it sounds like in your original MKV file, the audio is not synced with the video so you had to stretch the audio track to match the video length, which is a sensible preprocessing step.

> There are multiple audio streams, but subaligner seems to correctly select the desired audio stream for now. Does it know from the stream metadata which audio stream is correct based on the language?

No, it will select the first one if you have multiple audio tracks, unless the track index can be passed in via sth like `-map`, ref., https://github.com/baxtree/subaligner/blob/f3050173a7d7d1044b2f6484987538196d25d9e4/subaligner/media_helper.py#L52

**Comment by starptr** [comment]
Oh I see, thanks for the explanation!

As for the audio offset, in my use case I don't think it is practical to preprocess the video. I believe the video container I have is a valid representation of a video with audio, so I think it makes more sense for subaligner to gracefully handle the offset. (After all, you're probably creating/aligning your subtitles to use with a video container, not just the audio stream!) Let me know if you're interested in a small PR; otherwise congrats on your wonderful project!

**Comment by baxtree** [comment]
Yes, a PR will indeed help me to understand whether handling that kind of offsets should be within subaligner's scope. If possible, please make the PR general rather than specific to MKV container files. Thanks.
